version: '3.1'
networks:
  dev_nginx:
    external: false

services:
  nginx:
    container_name: dev_nginx
    image: nginx:1.23.1
    ports:
      - "80:8080"
    restart: always
    networks:
      - dev_nginx
    volumes:
      - ${NGINX_CONFIG_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${WORDPRESS_DIR}:/opt/www/wordpress
  phpfpm:
    container_name: dev_fpm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - dev_nginx
    volumes:
      - ${WORDPRESS_DIR}:/opt/www/wordpress
